#!/usr/bin/env sh

# Layout config
yabai -m config window_gap                   6
yabai -m config window_placement             second_child
yabai -m config layout                       bsp
# yabai -m config bottom_padding               100

# active window border settings
yabai -m config \
    window_border_width     4       \
    window_border_radius    12      \
    window_border_blur      off     \
    window_border_hidpi     on      \
    window_border           on      \
    active_window_border_color  0xdd02fa82

# set float layout for MBP display
space_indices_on_mbp_display="$(
    yabai -m query --displays \
        | jq -e 'map(select(.uuid == "CDDF5C97-65EE-5677-9D34-B89A46EB822A")) | .[0].spaces[]'
)"
for index in "$space_indices_on_mbp_display"
do
    yabai -m config --space "$index" layout stack
done

# Mouse
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise

# Debug
yabai -m config debug_output on

# Rules
yabai -m rule --add app="^Calendar$"           manage=off
yabai -m rule --add app="^Dictionary$"         manage=off
yabai -m rule --add app="^Disk Utility$"       manage=off
yabai -m rule --add app="^Postlab$"            manage=off
yabai -m rule --add app="^Simulator$"          manage=off
yabai -m rule --add app="^System Preferences$"  manage=off
yabai -m rule --add app="^Electron$"            manage=off
yabai -m rule --add app="^システム環境設定$"       manage=off
yabai -m rule --add app="^カレンダー$"            manage=off
yabai -m rule --add app="^メール$"              manage=off
yabai -m rule --add app="^DeepL$"               manage=off
yabai -m rule --add app="^Twitter$"             manage=off
yabai -m rule --add app="^1Password$"           manage=off
yabai -m rule --add app="^GitHub Desktop$"      manage=off
yabai -m rule --add app="^Dropbox$"             manage=off
yabai -m rule --add app="^Finder$"              manage=off
yabai -m rule --add app="^Telegram$"            manage=off
yabai -m rule --add app="^LINE$"                manage=off
yabai -m rule --add app="^メモ$"              manage=off

echo "yabai configuration loaded..."
